import { PieceField } from "../../models/piece-field";
import { King } from "../../models/pieces/king";
import { PawnBottom } from "../../models/pieces/pawn-bottom";

const fieldMap = {
  "A8": new PieceField("A8", null, "bg-white"),
  "B8": new PieceField("B8", null, "bg-black"),
  "C8": new PieceField("C8", null, "bg-white"),
  "D8": new PieceField("D8", null, "bg-black"),
  "E8": new PieceField("E8", new King("E8"), "bg-white"),
  "F8": new PieceField("F8", null, "bg-black"),
  "G8": new PieceField("G8", null, "bg-white"),
  "H8": new PieceField("H8", null, "bg-black"),
  "A7": new PieceField("A7", null, "bg-white"),
  "B7": new PieceField("B7", null, "bg-black"),
  "C7": new PieceField("C7", new PawnBottom("C7"), "bg-white"),
  "D7": new PieceField("D7", null, "bg-black"),
  "E7": new PieceField("E7", null, "bg-white"),
  "F7": new PieceField("F7", null, "bg-black"),
  "G7": new PieceField("G7", null, "bg-white"),
  "H7": new PieceField("H7", null, "bg-black"),
  "A6": new PieceField("A6", null, "bg-white"),
  "B6": new PieceField("B6", null, "bg-black"),
  "C6": new PieceField("C6", null, "bg-white"),
  "D6": new PieceField("D6", null, "bg-black"),
  "E6": new PieceField("E6", null, "bg-white"),
  "F6": new PieceField("F6", null, "bg-black"),
  "G6": new PieceField("G6", null, "bg-white"),
  "H6": new PieceField("H6", null, "bg-black"),
  "A5": new PieceField("A5", null, "bg-white"),
  "B5": new PieceField("B5", null, "bg-black"),
  "C5": new PieceField("C5", null, "bg-white"),
  "D5": new PieceField("D5", null, "bg-black"),
  "E5": new PieceField("E5", null, "bg-white"),
  "F5": new PieceField("F5", null, "bg-black"),
  "G5": new PieceField("G5", null, "bg-white"),
  "H5": new PieceField("H5", null, "bg-black"),
  "A4": new PieceField("A4", null, "bg-white"),
  "B4": new PieceField("B4", null, "bg-black"),
  "C4": new PieceField("C4", null, "bg-white"),
  "D4": new PieceField("D4", null, "bg-black"),
  "E4": new PieceField("E4", null, "bg-white"),
  "F4": new PieceField("F4", null, "bg-black"),
  "G4": new PieceField("G4", null, "bg-white"),
  "H4": new PieceField("H4", null, "bg-black"),
  "A3": new PieceField("A3", null, "bg-white"),
  "B3": new PieceField("B3", null, "bg-black"),
  "C3": new PieceField("C3", null, "bg-white"),
  "D3": new PieceField("D3", null, "bg-black"),
  "E3": new PieceField("E3", null, "bg-white"),
  "F3": new PieceField("F3", null, "bg-black"),
  "G3": new PieceField("G3", null, "bg-white"),
  "H3": new PieceField("H3", null, "bg-black"),
  "A2": new PieceField("A2", null, "bg-white"),
  "B2": new PieceField("B2", new PawnBottom("B2"), "bg-black"),
  "C2": new PieceField("C2", null, "bg-white"),
  "D2": new PieceField("D2", null, "bg-black"),
  "E2": new PieceField("E2", null, "bg-white"),
  "F2": new PieceField("F2", null, "bg-black"),
  "G2": new PieceField("G2", null, "bg-white"),
  "H2": new PieceField("H2", null, "bg-black"),
  "A1": new PieceField("A1", null, "bg-white"),
  "B1": new PieceField("B1", null, "bg-black"),
  "C1": new PieceField("C1", null, "bg-white"),
  "D1": new PieceField("D1", null, "bg-black"),
  "E1": new PieceField("E1", null, "bg-white"),
  "F1": new PieceField("F1", null, "bg-black"),
  "G1": new PieceField("G1", null, "bg-white"),
  "H1": new PieceField("H1", null, "bg-black"),
};

export default fieldMap;