import { PieceField } from "../../models/piece-field";
import { King } from "../../models/pieces/king";
import { PawnBottom } from "../../models/pieces/pawn-bottom";
import { PawnTop } from "../../models/pieces/pawn-top";

const fieldMap = {
  "A8": new PieceField("A8", null),
  "B8": new PieceField("B8", null),
  "C8": new PieceField("C8", null),
  "D8": new PieceField("D8", null),
  "E8": new PieceField("E8", new King("E8")),
  "F8": new PieceField("F8", null),
  "G8": new PieceField("G8", null),
  "H8": new PieceField("H8", null),
  "A7": new PieceField("A7", null),
  "B7": new PieceField("B7", null),
  "C7": new PieceField("C7", new PawnTop("C7")),
  "D7": new PieceField("D7", null),
  "E7": new PieceField("E7", null),
  "F7": new PieceField("F7", null),
  "G7": new PieceField("G7", null),
  "H7": new PieceField("H7", null),
  "A6": new PieceField("A6", null),
  "B6": new PieceField("B6", null),
  "C6": new PieceField("C6", null),
  "D6": new PieceField("D6", null),
  "E6": new PieceField("E6", null),
  "F6": new PieceField("F6", null),
  "G6": new PieceField("G6", null),
  "H6": new PieceField("H6", null),
  "A5": new PieceField("A5", null),
  "B5": new PieceField("B5", null),
  "C5": new PieceField("C5", null),
  "D5": new PieceField("D5", null),
  "E5": new PieceField("E5", null),
  "F5": new PieceField("F5", null),
  "G5": new PieceField("G5", null),
  "H5": new PieceField("H5", null),
  "A4": new PieceField("A4", null),
  "B4": new PieceField("B4", null),
  "C4": new PieceField("C4", null),
  "D4": new PieceField("D4", null),
  "E4": new PieceField("E4", null),
  "F4": new PieceField("F4", null),
  "G4": new PieceField("G4", null),
  "H4": new PieceField("H4", null),
  "A3": new PieceField("A3", null),
  "B3": new PieceField("B3", null),
  "C3": new PieceField("C3", null),
  "D3": new PieceField("D3", null),
  "E3": new PieceField("E3", null),
  "F3": new PieceField("F3", null),
  "G3": new PieceField("G3", null),
  "H3": new PieceField("H3", null),
  "A2": new PieceField("A2", null),
  "B2": new PieceField("B2", new PawnBottom("B2")),
  "C2": new PieceField("C2", null),
  "D2": new PieceField("D2", null),
  "E2": new PieceField("E2", null),
  "F2": new PieceField("F2", null),
  "G2": new PieceField("G2", null),
  "H2": new PieceField("H2", null),
  "A1": new PieceField("A1", null),
  "B1": new PieceField("B1", null),
  "C1": new PieceField("C1", null),
  "D1": new PieceField("D1", null),
  "E1": new PieceField("E1", null),
  "F1": new PieceField("F1", null),
  "G1": new PieceField("G1", null),
  "H1": new PieceField("H1", null),
};

export default fieldMap;